### ISSUE TITLE
not sure chat room link is working as intended

### ISSUE THREAD

**Issue by donboyd5** [comp-org/comp-ce#129]
The chat room link:

![image](https://user-images.githubusercontent.com/6538392/57371250-44685c80-7160-11e9-9d04-9fe938a6e541.png)

Produces this result:

![image](https://user-images.githubusercontent.com/6538392/57371296-64981b80-7160-11e9-9912-acc7db05e58f.png)

Maybe it's intended, or maybe it should be changed. If it is intended, newcomers like me may need a hint about what to do next.

**Comment by MattHJensen** [comment]
> @MattHJensen can you take a look at the visibility settings for the room to see if we can fix that?

Fixed. The room history is now public.

**Comment by hdoupe** [comment]
Thanks @MattHJensen for updating the access settings and @donboyd5 for bringing this up.
