### ISSUE TITLE
alert box shows "close" instead of "ok" on Safari

### ISSUE THREAD

**Issue by MattHJensen** [comp-org/comp-ce#142]
![image](https://user-images.githubusercontent.com/8301092/58898147-eaf43e80-86c7-11e9-9d39-fa20cc49931f.png)

It would be nice if this were "Ok" instead of "Close", like it is on Chrome. 

When I see this my eye is first drawn to "Close", and so before I read the message I think it wants me to close the site and there is something wrong.

**Comment by hdoupe** [comment]
Closed via #156--no more dialog box!
