### ISSUE TITLE
Liabilities table labels rows as "change" for non-change views

### ISSUE THREAD

**Issue by MaxGhenis** [comp-org/comp-ce#148]
I think the row labels should only say "Change" when the "Change" tab is active. p![image](https://user-images.githubusercontent.com/6076111/59152820-dd5cf280-8a00-11e9-99fb-8119e34308cc.png)

**Comment by hdoupe** [comment]
Thanks for your feedback @MaxGhenis. COMP isn't responsible for creating or formatting any of the results of the models that are on the platform--the models themselves have full control over this. You're welcome to reopen #148, #149, and #150 in the [Tax-Brain repo](https://github.com/PSLmodels/Tax-Brain/).

cc @andersonfrailey

**Comment by hdoupe** [comment]
> COMP isn't responsible for creating or formatting any of the results of the models that are on the platform--the models themselves have full control over this.

However, COMP could provide some functions to help models' results look nice on the webapp. For example, @peter-metz and @andersonfrailey have both spent a considerable amount of time trying to make HTML tables created from Pandas dataframes look nice in the browser. Abstracting that functionality out into [`compdevkit`](https://github.com/comp-org/COMP-Developer-Toolkit) or its own package would make it easier for projects to borrow that code and have nice looking tables, too.

**Comment by Peter-Metz** [comment]
I found that the quickest solution is to use [Bootstrap table classes](https://getbootstrap.com/docs/4.0/content/tables/) to format COMP output. At a minimum, it takes care of issues like columns width and shading.

cc: @andersonfrailey @MaxGhenis
