### ISSUE TITLE
Show "Change" tab by default

### ISSUE THREAD

**Issue by MaxGhenis** [comp-org/comp-ce#149]
The aggregate results tab by default shows the Current Law tab. I'd suggest showing the Change tab by default, as TaxBrain does.
![image](https://user-images.githubusercontent.com/6076111/59152858-8f94ba00-8a01-11e9-83e6-36464186f059.png)
![image](https://user-images.githubusercontent.com/6076111/59152860-96bbc800-8a01-11e9-9df1-1050d4fcccc9.png)

**Comment by hdoupe** [comment]
Closing #149. See my comment here https://github.com/comp-org/comp-ce/issues/148#issuecomment-500172521
