### ISSUE TITLE
Download results csv titles issue

### ISSUE THREAD

**Issue by rickecon** [comp-org/comp-ce#153]
I ran a `Tax-Calculator` simulation today on `CompModels.org`. I love the Bokeh plot that is included. However, I downloaded the results, and all the csv files that came in the zip file were missing titles. I had to download the json results in order to figure out the correspondence between the filenames and the csv titles. There must be a way to have the titles included in the csv files. The csv's could have more descriptive names, or a crosswalk text file or json could be included with the csv's.

**Comment by hdoupe** [comment]
The patch for #153 is live. All new runs will have the correct file names.
