### ISSUE TITLE
404 Error for link on Publishing Guide

### ISSUE THREAD

**Issue by jdebacker** [comp-org/comp-ce#160]
On the [Publishing Guide](https://docs.compmodels.org/publish/guide/) the link in "The second part documents..." is broken.

**Comment by hdoupe** [comment]
Thanks @jdebacker. That link should be https://docs.compmodels.org/publish/functions/

**Comment by hdoupe** [comment]
This is fixed now on [docs.compmodels.org](https://docs.compmodels.org). Thanks for the bug report @jdebacker.
