### ISSUE TITLE
Move + box to left side in My Simulations panel

### ISSUE THREAD

**Issue by MaxGhenis** [comp-org/comp-ce#186]
When I arrived at My Simulations, my first natural click was to PSLModels/TaxBrain, but that took me to a new simulation page. The + box on the right was what I was looking for to see my simulations. I'd personally find it more intuitive to move this to the left side to get users to the main purpose of the page more quickly.
![image](https://user-images.githubusercontent.com/6076111/61826453-4b297600-ae17-11e9-9dea-7b9315b7be52.png)

**Comment by MaxGhenis** [comment]
I also wonder if a > icon would be more natural, which then turns into a down arrow when clicked. The + icon is used on places like Google Drive to create a new instance.

**Comment by hdoupe** [comment]
Thanks for the suggestion @MaxGhenis. How's this look:

![Screenshot from 2019-07-24 17-01-26](https://user-images.githubusercontent.com/9206065/61828470-c77e8200-ae34-11e9-8f6a-fc3c5606258d.png)

I also played with the color a little:

![Screenshot from 2019-07-24 17-06-05](https://user-images.githubusercontent.com/9206065/61828776-791db300-ae35-11e9-80ad-a9442c7d8a7e.png)

**Comment by MaxGhenis** [comment]
Looks great!

**Comment by MaxGhenis** [comment]
I personally prefer the gray to green but both look good.

**Comment by hdoupe** [comment]
Thanks! Agreed, the green is a little aggressive for a down arrow.
